openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/sign:
    post:
      operationId: sign
      summary: "[sign]"
      description: |
        The sign method calculates a Klaytn-specific signature with: sign(keccak256("\x19Klaytn Signed Message:\n" + len(message) + message)))
        
        Adding a prefix to the message makes the calculated signature recognizable as a Klaytn-specific signature. This prevents misuse where a malicious DApp can sign arbitrary data (e.g., transaction) and use the signature to impersonate the victim.
        
        See personal_ecRecover to verify the signature.

        | Client | Method invocation |
        |-----|-----|
        | Console   | personal.sign(message, account, password) |
        | RPC | {"method": "personal_sign", "params": [message, account, password]} |

        **JSONRPC:** `personal_sign`
      tags:
        - personal

      parameters:
        - name: message
          required: true
          schema:
            type: string
          description: A message to sign.
          in: query
        - name: account
          required: true
          schema:
            type: string
          description: The account address.
          in: query
        - name: password
          required: true
          schema:
            type: string
          description: The pass phrase used for signing.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/PersonalSignReq"

      responses:
        200:
          description: Return the a signature.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        description: A signature.
                        example: "0xa3f20717a250c2b0b729b7e5becbff67fdaef7e0699da4de7ca5895b02a170a12d887fd3b17bfdce3481f10bea41f45ba9f709d39ce8325427b57afcfc994cee1b"
      
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/sign.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: ""
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    PersonalSignReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'personal_sign'
        params:
          type: array
          items:
            anyOf:
              - type: string
                title: Message
                description: A message to sign.
              - type: string
                title: Account
                description: The account address.
              - type: string
                title: Password
                description: The pass phrase used for signing.
          example: ["0xdead", "0x9b2055d370f73ec7d8a03e965129118dc8f5bf83", "gr8=B!0@uc$b"]

