/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetRewardsRequest from '../model/GetRewardsRequest';
import GetRewardsResponse from '../model/GetRewardsResponse';
import JsonRpcResponse from '../model/JsonRpcResponse';
import OneOflongstring from '../model/OneOflongstring';

/**
* Klay service.
* @module api/KlayApi
* @version 1.10.0
*/
export default class KlayApi {

    /**
    * Constructs a new KlayApi. 
    * @alias module:api/KlayApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getRewards operation.
     * @callback module:api/KlayApi~getRewardsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetRewardsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * [getRewards] Find distributed block rewards
     * Returns distributed block rewards information at the latest block number  **JSONRPC:** `klay_getRewards` 
     * @param {Object} opts Optional parameters
     * @param {module:model/GetRewardsBlockNumberOrTagParameter} opts.blockNumberOrTag 
     * @param {module:model/GetRewardsRequest} opts.getRewardsRequest 
     * @param {module:api/KlayApi~getRewardsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetRewardsResponse}
     */
    getRewards(opts, callback) {
      opts = opts || {};

      let postBody = new GetRewardsRequest(undefined, undefined, undefined);
      postBody.params = [];
      
      if(opts['blockNumberOrTag']) {
        postBody.params.push(opts['blockNumberOrTag']);
      }

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'text/plain'];
      let returnType = GetRewardsResponse;
      return this.apiClient.callApi(
        '/klay/getRewards', 'POST', null, null, null, null,
        postBody, authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
