openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/createAccessList:
    post:
      summary: "[createAccessList]"
      tags:
        - eth
      operationId: createAccessList
      description: |
        CreateAccessList creates a EIP-2930 type AccessList for the given transaction. Reexec and BlockNrOrHash can be specified to create the accessList on top of a certain state.
        
        **JSONRPC:** `eth_createAccessList`

      parameters:
        - name: transactionArgs
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/EthTransactionArgs"
        - name: blockNumberOrHash
          in: query
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthCreateAccessListReq"

      responses:
        200:
          description: Return accessList
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthCreateAccessListResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/others/createAccessList.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
#        - lang: "javascript"
#          label: "Javascript"
#          source:
#            $ref: "../../../code-samples/javascript/eth/transaction/fillTransaction.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #    $ref: ""

components:
  schemas:
    EthCreateAccessListReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: "eth_createAccessList"
        params:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/EthTransactionArgs"
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

    EthTransactionArgs:
      type: object
      title: TransactionArgs
      properties:
        accessList:
            type: array
            items:
                type: object
                properties:
                  address:
                      type: string
                  storageKeys:
                      type: array
                      items:
                        type: string
                        description: Hex representation of a Keccak 256 hash
        chainId:
          type: string
        data:
          type: string
        from:
          type: string
        gas:
          type: string
        gasPrice:
          type: string
        input:
          type: string
        maxFeePerGas:
          type: string
        maxPriorityFeePerGas:
          type: string
        nonce:
          type: string
        to:
          type: string
        value:
          type: string

    EthCreateAccessListResp:
      type: object
      properties:
        result:
          type: object
          properties:
            accessList:
              type: array
              items:
                type: object
                properties:
                  address:
                    type: string
                  storageKeys:
                    type: array
                    items:
                      type: string
                      description: Hex representation of a Keccak 256 hash
            error:
              type: string
            gasUsed:
              type: string


