/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package web3rpc.client

import io.kotest.core.spec.style.BehaviorSpec
import io.kotest.matchers.shouldBe
import org.openapitools.codegen.CodegenConfig
import java.util.*

class KlaytnKotlinClientCodeGenTest : BehaviorSpec({
    Given("Klaytn Koltin code generator") {
        When("Load by ServiceLoader") {
            Then("should be existed") {
                val loader = ServiceLoader.load(
                    CodegenConfig::class.java,
                    CodegenConfig::class.java.classLoader
                )

                for (config in loader) {
                    println(config.name)
                }
                loader.find { i -> i.name == KlaytnKotlinClientCodegen.clientName}?.name.shouldBe(KlaytnKotlinClientCodegen.clientName)
            }
        }
        When("Model file name set to KlaytnModel") {
            Then("return 'klaytn-model as camel case") {
                val codeGen = KlaytnJavascriptClientCodegen()
                codeGen.toModelFilename("KlaytnModel").shouldBe("KlaytnModel")
            }
        }
    }
})
