openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/deriveAccount:
    post:
      operationId: deriveAccount
      summary: "[deriveAccount]"
      description: |
        Requests a HD wallet to derive a new account, optionally pinning it for later reuse.

        **JSONRPC:** `personal_deriveAccount`
      tags:
        - personal

      parameters:
        - name: URL
          required: true
          schema:
            type: string
          description: Wallet url
          in: query
        - name: path
          required: true
          schema:
            type: string
          description: derivation path
          in: query 
        - name: pin
          required: false
          schema:
            type: boolean
          description: optionally pinning
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/PersonalDeriveAccountReq"

      responses:
        200:
          description: Return the address of the new account.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        description: The address of the new account.
                        example: "0xed1b12248aee85a32aead06c7789d3fcdcd4dae6"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/deriveAccount.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/personal/PersonalDeriveAccountExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/personal/deriveAccount.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/personal/deriveAccount.py"

components:
  schemas:
    PersonalDeriveAccountReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'personal_deriveAccount'
        params:
          type: array
          items:
            properties:
              URL:
                type: string
                title: Url
                description: Wallet url
              Path:
                type: string
                title: Path
                description: derivation path
              Pin:
                type: boolean
                title: Pin
                description: optionally pinning
          example: [ "url", "path", true]

