openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/ecRecover:
    post:
      operationId: ecRecover
      summary: "[ecRecover]"
      description: |
        ecRecover returns the address associated with the private key that was used to calculate the signature in personal_sign.

        **JSONRPC:** `personal_ecRecover`
      tags:
        - personal

      parameters:
        - name: message
          required: true
          schema:
            type: string
          description: A message.
          in: query
        - name: signature
          required: true
          schema:
            type: string
          description: The signature.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/PersonalEcRecoverReq"

      responses:
        200:
          description: Return the account address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        description: The account address.
                        example: "0xda04fb00e2cb5745cef7d8c4464378202a1673ef"
      
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/ecRecover.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/personal/PersonalEcRecoverExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/personal/ecRecover.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/personal/ecRecover.py"

components:
  schemas:
    PersonalEcRecoverReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'personal_ecRecover'
        params:
          type: array
          items:
            properties:
              Message:
                type: string
                title: Message
                description: A message.
              Signature:
                type: string
                title: Signature
                description: The signature.
          example: ["0xdead","0xccb8cce176b01fdc8f7ac3c101b8eb3b9005e938a60800e517624419dd8b7fba0e4598bdf1c4fa1743e1288e89b8b7090cc11f4b3640aafcbc71896ec73eec241b"]

