openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/listAccounts:
    post:
      operationId: listAccounts
      summary: "personal_listAccounts"
      description: |
        Returns all the Klaytn account addresses of all keys in the key store.

        **JSONRPC:** `personal_listAccounts`
      tags:
        - personal

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                  properties:
                    method:
                      type: string
                      default: 'personal_listAccounts'

      responses:
        200:
          description: Returns all the Klaytn account addresses of all keys in the key store.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        description: The list of all the Klaytn account addresses
                        example: ["0x5e97870f263700f46aa00d967821199b9bc5a120", "0x3d80b31a78c30fc628f20b2c89d7ddbf6e53cedc"]

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/listAccounts.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/personal/PersonalListAccountsExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/personal/listAccounts.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/personal/listAccounts.py"
