openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getCode:
    post:
      operationId: getCode
      summary: "[Account-getCode]"
      description: |
        Returns code at a given address.

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.*

        **JSONRPC:** `klay_getCode`
      tags:
        - klay

      parameters:
        - name: account
          required: true
          schema:
            type: string
            format: 20-byte DATA
          description: Address
          in: query
        - name: blockNumberOrHashOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetCodeReq"

      responses:
        200:
          description: Returns code at a given address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: DATA
                        description: The code from the given address.
                        example: "0x600160008035811a818181146012578301005b601b6001356025565b8060005260206000f25b600060078202905091905056"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/getCode.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/account/KlayGetCodeExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/account/getCode.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/account/getCode.py"

components:
  schemas:
    KlayGetCodeReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getCode'
        params:
          type: array
          items:
            properties:
              Address:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              BlockNumberOrHashOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  ["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x2"]
