openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/account/getTransactionCount:
    post:
      operationId: getTransactionCount
      summary: "[Account] klay_getTransactionCount"
      description: |
        Returns the number of transactions sent from an address.

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available*

        **JSONRPC:** `klay_getTransactionCount`
      tags:
        - klay

      parameters:
        - name: Address
          required: true
          schema:
            type: string
            format: 20-byte DATA
          description: Address
          in: query
        - name: blockNumberOrHashOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetTransactionCountReq"

      responses:
        200:
          description: Returns the number of transactions sent from an address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetTransactionCountResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/getTransactionCount.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/account/KlayGetTransactionCountExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/account/getTransactionCount.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/account/getTransactionCount.py"

components:
  schemas:
    KlayGetTransactionCountReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getTransactionCount'
        params:
          type: array
          items:
            properties:
              Address:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              BlockNumberOrHashOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  ["0xc94770007dda54cF92009BFF0dE90c06F603a09f","latest"]

    KlayGetTransactionCountResp:
      type: object
      properties:
        result:
          type: string
          format: hex
          description: Integer of the number of transactions send from this address.
          example: "0x1"
