openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getRawTransactionByBlockNumberAndIndex:
    post:
      operationId: getRawTransactionByBlockNumberAndIndex
      summary: "[getRawTransactionByBlockNumberAndIndex]"
      tags:
        - klay
      description: |
        GetRawTransactionByBlockNumberAndIndex returns the bytes of the transaction for the given block number and index.

        **JSONRPC:** `klay_getRawTransactionByBlockNumberAndIndex`

      parameters:
        - name: blockNumberOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in default block parameter.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
        - name: transactionIndex
          required: true
          schema:
            type: string
            format: hex
          description: The transaction index position.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetRawTransactionByBlockNumberAndIndexReq"

      responses:
        200:
          description: Returns the bytes of the transaction for the given block number and index.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetRawTransactionByBlockNumberAndIndexResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/others/getRawTransactionByBlockNumberAndIndex.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/others/getRawTransactionByBlockNumberAndIndex.py"

components:
  schemas:
    KlayGetRawTransactionByBlockNumberAndIndexReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getRawTransactionByBlockNumberAndIndex'
        params:
          type: array
          items:
            anyOf:
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              - type: string
                format: hex
                title: transactionIndex
                description: The transaction index position.
          example:  ["0x27", "0x0"]

    KlayGetRawTransactionByBlockNumberAndIndexResp:
      type: object
      properties:
        result:
          type: string
          description: Hex representation of some bytes
          example: "0x0"
