openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/dumpStateTrie:
    post:
      operationId: dumpStateTrie
      summary: "[dumpStateTrie]"
      description: |
        Retrieves all state/storage tries of the given state root.

        **JSONRPC:** `debug_dumpStateTrie`
      tags:
        - debug

      parameters:
        - name: number
          required: true
          schema:
            type: string
            format: hex
          description: The block number.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: "debug_dumpStateTrie"
                    params:
                      type: array
                      items:
                        oneOf:
                        - title: number
                          type: integer
                        - type: string
                          format: hex
                      description: "The block number."
                      example: ["0x80"]

      responses:
        200:
          description: Return the dump state Trie result
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/DumpStateTrieResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/blockchainInspection/dumpStateTrie.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klaytnDebug/blockchainInspection/dumpStateTrie.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    DumpStateTrieResp:
      type: object
      properties:
        result:
          type: object
          description: The dump state Trie result
          properties:
            root:
              type: string
            tries:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  hash:
                    type: string
                  parent:
                    type: string
                  path:
                    type: string

          example:
            {
              "root": "0xd62748ae1ba12975f61470f06912c05d92b4366611338e57ee165802d392e628",
              "tries":
                [
                  {
                    "type": "state",
                    "hash": "0xd62748ae1ba12975f61470f06912c05d92b4366611338e57ee165802d392e628",
                    "parent": "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "path": "0x"
                  }
                ]
            }
