openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/getBadBlocks:
    post:
      operationId: getBadBlocks
      summary: "[getBadBlocks]"
      description: |
        Returns a list of the last 'bad blocks' that the client has seen on the network.

        | Client | Method invocation |
        |-----|-----|
        | Console   | debug.getBadBlocks() |
        | RPC | {"method": "debug_getBadBlocks", "params": []} |

        **JSONRPC:** `debug_getBadBlocks`
      tags:
        - debug

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"

      responses:
        200:
          description: Return a list of the last 'bad blocks'.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: array
                        description: JSON list of block-hashes
                        items:
                          type: object
                        example: []
      
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/blockchainInspection/getBadBlocks.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: ""
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""