openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /kaia/block/getBlockByHash:
    post:
      operationId: .getBlockByHash
      summary: "[Block] kaia_getBlockByHash"
      description: |
        Returns information about a block by hash. This API works only on RPC call, not on JavaScript console.
        
        **JSONRPC:** `kaia_getBlockByHash`

      tags:
        - kaia

      parameters:
        - name: hashOfBlock
          required: true
          schema:
            type: string
            format: 32-byte DATA
          description: Hash of a block
          in: query
        - name: returnTransactionObject
          in: query
          description: If true it returns the full transaction objects, if false only the hashes of the transactions.
          required: true
          schema:
            type: boolean

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KaiaGetBlockByHashReq"

      responses:
        200:
          description: Returns information about a block by hash
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KaiaGetBlockByHashResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/kaia/block/getBlockByHash.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/kaia/block/KaiaGetBlockByHashExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/kaia/block/getBlockByHash.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/kaia/block/getBlockByHash.py"

components:
  schemas:
    KaiaGetBlockByHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'kaia_getBlockByHash'
        params:
          type: array
          items:
            properties:
              BlockHash:
                type: string
                title: HashOfBlock
                format: 32-byte DATA
                description: Hash of a block.
              ReturnTransactionObject:
                type: boolean
                title: ReturnTransactionObject
                description: If true it returns the full transaction objects, if false only the hashes of the transactions.
          example:  ["0xba647d41423faeebe8a7c64737d284fc2eba6f0388a3e1ebf6243db509ec1577", true]

    KaiaGetBlockByHashResp:
      type: object
      properties:
        result:
          $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/KaiaBlock"
