openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/pendingTransactions:
    post:
      operationId: pendingTransactions
      summary: "[pendingTransactions]"
      tags:
        - eth
      description: |
        Returns the transactions that are in the transaction pool and have a from address that is one of the accounts this node manages.

        **JSONRPC:** `eth_pendingTransactions`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/ethPendingTransactionsReq"

      responses:
        200:
          description: An array of transactions. For the returned transaction object.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/ethPendingTransactionsResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/transaction/pendingTransactions.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/transaction/pendingTransactions.js"
        - lang: "python"
          label: "Python"
          source:
           $ref: "../../../code-samples/python/eth/transaction/pendingTransactions.py"

components:
  schemas:
    ethPendingTransactionsReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: "eth_pendingTransactions"

    ethPendingTransactionsResp:
      type: object
      properties:
        result:
          type: array
          description: An array of transactions.
          items:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TransactionArgs"
          example:
            [
              {
                "blockHash": null,
                "blockNumber": null,
                "from": "0xca7a99380131e6c76cfa622396347107aeedca2d",
                "gas": "0x5208",
                "gasPrice": "0x5d21dba00",
                "maxFeePerGas": "0x5d21dba00",
                "maxPriorityFeePerGas": "0x5d21dba00",
                "hash": "0xb5cd867ccc356b86634092919fb1acf4e315618d6c804df3ec3d30d66b6baba5",
                "input": "0x",
                "nonce": "0xdb",
                "to": "0x3e2ac308cd78ac2fe162f9522deb2b56d9da9499",
                "transactionIndex": null,
                "value": "0x1",
                "type": "0x2",
                "accessList": [],
                "chainId": "0x2edaf",
                "v": "0x1",
                "r": "0x73992e7c3b9f6cd73176969efa8509d8e9ae0739e24b03d514508f8ef03f19ef",
                "s": "0x7035dd8639e82ea3ba922ff02e1f21f4cff92d0de33050934f5c70908d61e8c3",
              },
            ]
