openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - klay
servers:
  - url: http://localhost:8551
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:

  # klay/account
  /klay/account/accountCreated:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/accountCreated.yaml#/paths/~1klay~1account~1accountCreated
  /klay/account/accounts:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/accounts.yaml#/paths/~1klay~1account~1accounts
  /klay/account/decodeAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/decodeAccountKey.yaml#/paths/~1klay~1account~1decodeAccountKey
  /klay/account/getAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/getAccountKey.yaml#/paths/~1klay~1account~1getAccountKey
  /klay/account/getCode:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/getCode.yaml#/paths/~1klay~1account~1getCode
  /klay/account/encodeAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/encodeAccountKey.yaml#/paths/~1klay~1account~1encodeAccountKey
  /klay/account/getAccount:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/getAccount.yaml#/paths/~1klay~1account~1getAccount
  /klay/account/getBalance:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/getBalance.yaml#/paths/~1klay~1account~1getBalance
  /klay/account/sign:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/sign.yaml#/paths/~1klay~1account~1sign
  /klay/account/getTransactionCount:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/getTransactionCount.yaml#/paths/~1klay~1account~1getTransactionCount
  /klay/account/isContractAccount:
    $ref: ../../web3rpc/rpc-specs/paths/klay/account/isContractAccount.yaml#/paths/~1klay~1account~1isContractAccount

  # klay/block
  /klay/block/blockNumber:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/blockNumber.yaml#/paths/~1klay~1block~1blockNumber
  /klay/block/getBlockByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockByHash.yaml#/paths/~1klay~1block~1getBlockByHash
  /klay/block/getBlockReceipts:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockReceipts.yaml#/paths/~1klay~1block~1getBlockReceipts
  /klay/block/getBlockTransactionCountByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockTransactionCountByNumber.yaml#/paths/~1klay~1block~1getBlockTransactionCountByNumber
  /klay/block/getBlockWithConsensusInfoByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockWithConsensusInfoByNumber.yaml#/paths/~1klay~1block~1getBlockWithConsensusInfoByNumber
  /klay/block/getCommittee:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getCommittee.yaml#/paths/~1klay~1block~1getCommittee
  /klay/block/getCommitteeSize:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getCommitteeSize.yaml#/paths/~1klay~1block~1getCommitteeSize
  /klay/block/getCouncil:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getCouncil.yaml#/paths/~1klay~1block~1getCouncil
  /klay/block/getCouncilSize:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getCouncilSize.yaml#/paths/~1klay~1block~1getCouncilSize
  /klay/block/getBlockByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockByNumber.yaml#/paths/~1klay~1block~1getBlockByNumber
  /klay/block/getBlockTransactionCountByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockTransactionCountByHash.yaml#/paths/~1klay~1block~1getBlockTransactionCountByHash
  /klay/block/getHeaderByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getHeaderByNumber.yaml#/paths/~1klay~1block~1getHeaderByNumber
  /klay/block/getHeaderByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getHeaderByHash.yaml#/paths/~1klay~1block~1getHeaderByHash
  /klay/getRewards:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getRewards.yaml#/paths/~1klay~1block~1getRewards
  /klay/getStorageAt:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getStorageAt.yaml#/paths/~1klay~1block~1getStorageAt
  /klay/block/syncing:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/syncing.yaml#/paths/~1klay~1block~1syncing
  /klay/block/getBlockWithConsensusInfoByNumberRange:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockWithConsensusInfoByNumberRange.yaml#/paths/~1klay~1block~1getBlockWithConsensusInfoByNumberRange
  /klay/block/getBlockWithConsensusInfoByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/block/getBlockWithConsensusInfoByHash.yaml#/paths/~1klay~1block~1getBlockWithConsensusInfoByHash

  # klay/transaction
  /klay/transaction/call:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/call.yaml#/paths/~1klay~1transaction~1call
  /klay/transaction/getDecodedAnchoringTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml#/paths/~1klay~1transaction~1getDecodedAnchoringTransactionByHash
  /klay/transaction/estimateGas:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/estimateGas.yaml#/paths/~1klay~1transaction~1estimateGas
  /klay/transaction/getTransactionByBlockNumberAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionByBlockNumberAndIndex.yaml#/paths/~1klay~1transaction~1getTransactionByBlockNumberAndIndex
  /klay/transaction/getTransactionBySenderTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionBySenderTxHash.yaml#/paths/~1klay~1transaction~1getTransactionBySenderTxHash
  /klay/transaction/getTransactionByBlockHashAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionByBlockHashAndIndex.yaml#/paths/~1klay~1transaction~1getTransactionByBlockHashAndIndex
  /klay/transaction/getTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionByHash.yaml#/paths/~1klay~1transaction~1getTransactionByHash
  /klay/transaction/getTransactionReceipt:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionReceipt.yaml#/paths/~1klay~1transaction~1getTransactionReceipt
  /klay/transaction/sendRawTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/sendRawTransaction.yaml#/paths/~1klay~1transaction~1sendRawTransaction
  /klay/transaction/estimateComputationCost:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/estimateComputationCost.yaml#/paths/~1klay~1transaction~1estimateComputationCost
  /klay/transaction/sendTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/sendTransaction.yaml#/paths/~1klay~1transaction~1sendTransaction
  /klay/transaction/sendTransactionAsFeePayer:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/sendTransactionAsFeePayer.yaml#/paths/~1klay~1transaction~1sendTransactionAsFeePayer
  /klay/transaction/signTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/signTransaction.yaml#/paths/~1klay~1transaction~1signTransaction
  /klay/transaction/signTransactionAsFeePayer:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/signTransactionAsFeePayer.yaml#/paths/~1klay~1transaction~1signTransactionAsFeePayer
  /klay/transaction/pendingTransactions:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/pendingTransactions.yaml#/paths/~1klay~1transaction~1pendingTransactions
  /klay/transaction/getTransactionReceiptBySenderTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml#/paths/~1klay~1transaction~1getTransactionReceiptBySenderTxHash
  /klay/createAccessList:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/createAccessList.yaml#/paths/~1klay~1transaction~1createAccessList
  /klay/getRawTransactionByBlockHashAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getRawTransactionByBlockHashAndIndex.yaml#/paths/~1klay~1transaction~1getRawTransactionByBlockHashAndIndex
  /klay/getRawTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getRawTransactionByHash.yaml#/paths/~1klay~1transaction~1getRawTransactionByHash
  /klay/resend:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/resend.yaml#/paths/~1klay~1transaction~1resend
  /klay/getRawTransactionByBlockNumberAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/klay/transaction/getRawTransactionByBlockNumberAndIndex.yaml#/paths/~1klay~1transaction~1getRawTransactionByBlockNumberAndIndex
 
  # klay/configuration
  /klay/configuration/chainID:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/chainID.yaml#/paths/~1klay~1configuration~1chainID
  /klay/configuration/clientVersion:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/clientVersion.yaml#/paths/~1klay~1configuration~1clientVersion
  /klay/configuration/gasPriceAt:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/gasPriceAt.yaml#/paths/~1klay~1configuration~1gasPriceAt
  /klay/configuration/gasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/gasPrice.yaml#/paths/~1klay~1configuration~1gasPrice
  /klay/configuration/isParallelDBWrite:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/isParallelDBWrite.yaml#/paths/~1klay~1configuration~1isParallelDBWrite
  /klay/configuration/isSenderTxHashIndexingEnabled:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/isSenderTxHashIndexingEnabled.yaml#/paths/~1klay~1configuration~1isSenderTxHashIndexingEnabled
  /klay/configuration/protocolVersion:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/protocolVersion.yaml#/paths/~1klay~1configuration~1protocolVersion
  /klay/configuration/rewardbase:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/rewardBase.yaml#/paths/~1klay~1configuration~1rewardbase
  /klay/configuration/getChainConfig:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/getChainConfig.yaml#/paths/~1klay~1configuration~1getChainConfig
  /klay/configuration/forkStatus:
    $ref: ../../web3rpc/rpc-specs/paths/klay/configuration/forkStatus.yaml#/paths/~1klay~1configuration~1forkStatus

  # klay/filter
  /klay/filter/getFilterChanges:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/getFilterChanges.yaml#/paths/~1klay~1filter~1getFilterChanges
  /klay/filter/getFilterLogs:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/getFilterLogs.yaml#/paths/~1klay~1filter~1getFilterLogs
  /klay/filter/newBlockFilter:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/newBlockFilter.yaml#/paths/~1klay~1filter~1newBlockFilter
  /klay/filter/newPendingTransactionFilter:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/newPendingTransactionFilter.yaml#/paths/~1klay~1filter~1newPendingTransactionFilter
  /klay/filter/uninstallFilter:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/uninstallFilter.yaml#/paths/~1klay~1filter~1uninstallFilter
  /klay/filter/unsubscribe:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/unsubscribe.yaml#/paths/~1klay~1filter~1unsubscribe
  /klay/filter/getLogs:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/getLogs.yaml#/paths/~1klay~1filter~1getLogs
  /klay/filter/subscribe:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/subscribe.yaml#/paths/~1klay~1filter~1subscribe
  /klay/filter/newFilter:
    $ref: ../../web3rpc/rpc-specs/paths/klay/filter/newFilter.yaml#/paths/~1klay~1filter~1newFilter

  # klay/gas
  /klay/gas/feeHistory:
    $ref: ../../web3rpc/rpc-specs/paths/klay/gas/feeHistory.yaml#/paths/~1klay~1gas~1feeHistory
  /klay/gas/lowerBoundGasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/klay/gas/lowerBoundGasPrice.yaml#/paths/~1klay~1gas~1lowerBoundGasPrice
  /klay/gas/upperBoundGasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/klay/gas/upperBoundGasPrice.yaml#/paths/~1klay~1gas~1upperBoundGasPrice
  /klay/gas/maxPriorityFeePerGas:
    $ref: ../../web3rpc/rpc-specs/paths/klay/gas/maxPriorityFeePerGas.yaml#/paths/~1klay~1gas~1maxPriorityFeePerGas

  # klay/miscellaneous
  /klay/miscellaneous/sha3:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/sha3.yaml#/paths/~1klay~1miscellaneous~1sha3
  /klay/miscellaneous/getStakingInfo:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/getStakingInfo.yaml#/paths/~1klay~1miscellaneous~1getStakingInfo
  /klay/miscellaneous/recoverFromTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/recoverFromTransaction.yaml#/paths/~1klay~1miscellaneous~1recoverFromTransaction
  /klay/miscellaneous/recoverFromMessage:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/recoverFromMessage.yaml#/paths/~1klay~1miscellaneous~1recoverFromMessage
  /klay/miscellaneous/getProof:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/getProof.yaml#/paths/~1klay~1miscellaneous~1getProof
  /klay/miscellaneous/nodeAddress:
    $ref: ../../web3rpc/rpc-specs/paths/klay/miscellaneous/nodeAddress.yaml#/paths/~1klay~1miscellaneous~1nodeAddress