openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - net
servers:
  - url: http://localhost:8551
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:

  # net
  /net/listening:
    $ref: ../../web3rpc/rpc-specs/paths/net/listening.yaml#/paths/~1net~1listening
  /net/networkID:
    $ref: ../../web3rpc/rpc-specs/paths/net/networkID.yaml#/paths/~1net~1networkID
  /net/peerCount:
    $ref: ../../web3rpc/rpc-specs/paths/net/peerCount.yaml#/paths/~1net~1peerCount
  /net/peerCountByType:
    $ref: ../../web3rpc/rpc-specs/paths/net/peerCountByType.yaml#/paths/~1net~1peerCountByType
  /net/version:
    $ref: ../../web3rpc/rpc-specs/paths/net/version.yaml#/paths/~1net~1version