openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - txpool
servers:
  - url: http://localhost:8551
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:

  # txpool
  /txpool/content:
    $ref: ../../web3rpc/rpc-specs/paths/txpool/content.yaml#/paths/~1txpool~1content
  /txpool/inspect:
    $ref: ../../web3rpc/rpc-specs/paths/txpool/inspect.yaml#/paths/~1txpool~1inspect
  /txpool/status:
    $ref: ../../web3rpc/rpc-specs/paths/txpool/status.yaml#/paths/~1txpool~1status