openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/transaction/call:
    post:
      summary: "[Transaction] eth_call"
      tags:
        - eth
      operationId: call
      description: |
        Executes a new message call immediately, without creating a transaction on the block chain. The eth_call method can be used to query internal contract state, to execute validations coded into a contract or even to test what the effect of a transaction would be without running it live.

        **JSONRPC:** `eth_call`

      parameters:
        - name: callObject
          in: query
          description: The transaction call object. See the next table for the object's properties.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/EthCallObject"
        - name: blockNumberOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in default block parameter.The block number is mandatory and defines the context (state) against which the specified transaction should be executed.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
        - name: stateOverrideSet
          in: query
          description: The state override set is an optional address-to-state mapping, where each entry specifies some state to be ephemerally overridden prior to executing the call.
          required: false
          schema:
            $ref: "#/components/schemas/StateOverrideSet"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayCallReq"

      responses:
        200:
          description: The returned data of the call
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayCallResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/transaction/call.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/transaction/EthCallExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/transaction/call.js"
        - lang: "Python"
          label: "Python"
          source:
           $ref: "../../../code-samples/python/eth/transaction/call.py"

components:
  schemas:
    KlayCallReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'eth_call'
        params:
          type: array
          items:
            properties:
              EthCallObject:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/EthCallObject"
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              StateOverrideSet:
                $ref: "#/components/schemas/StateOverrideSet"
          example: [{"from": "0xca7a99380131e6c76cfa622396347107aeedca2d", "to": "0xbE3892d33620bE5aca8c75D39e7401871194d290", "input": "0x2e64cec1"}, "latest", {"0xbE3892d33620bE5aca8c75D39e7401871194d290": {"code":"0x6080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632e64cec114604e5780636057361d146076575b600080fd5b348015605957600080fd5b50606060a0565b6040518082815260200191505060405180910390f35b348015608157600080fd5b50609e6004803603810190808035906020019092919050505060a9565b005b60008054905090565b80600081905550505600a165627a7a723058207783dba41884f73679e167576362b7277f88458815141651f48ca38c25b498f80029"}}]

    StateOverrideSet:
      type: object
      description: The state override set is an optional address-to-state mapping, where each entry specifies some state to be ephemerally overridden prior to executing the call.
      properties:
        balance:
          type: integer
          format: int64
          description: (optional) Fake balance to set for the account before executing the call.
        nonce:
          type: integer
          format: int64
          description: (optional) Fake nonce to set for the account before executing the call.
        code:
          type: string
          format: DATA
          description: (optional) Fake EVM bytecode to inject into the account before executing the call.
        state:
          type: object
          description: (optional) Fake key-value mapping to override all slots in the account storage before executing the call.
        stateDiff:
          type: object
          description: (optional) Fake key-value mapping to override individual slots in the account storage before executing the call.

    KlayCallResp:
      type: object
      properties:
        result:
          type: string
          example: "0x0000000000000000000000000000000000000000000000000000000000000000"

