openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/estimateGas:
    post:
      summary: "[Transaction-estimateGas]"
      tags:
        - eth
      operationId: estimateGas
      description: |
        Generates and returns an estimate of how much gas is necessary to allow the transaction to complete. The transaction will not be added to the blockchain. Note that the estimate may be significantly more than the amount of gas actually used by the transaction, for a variety of reasons including EVM mechanics and node performance.

        **JSONRPC:** `eth_estimateGas`

      parameters:
        - name: callObject
          in: query
          description: The transaction call object. See the next table for the object's properties.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/EthCallObject"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthEstimateGasReq"

      responses:
        200:
          description: Return the amount of gas used.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthEstimateGasResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/transaction/estimateGas.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/transaction/EthEstimateGasExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/transaction/estimateGas.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/transaction/estimateGas.py"

components:
  schemas:
    EthEstimateGasReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'eth_estimateGas'
        params:
          type: array
          items:
            anyOf:
              - allOf:
                  - title: callObject
                  - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/EthCallObject"
          description: The transaction call object. See the next table for the object's properties.
          example: [{"from": "0x3f71029af4e252b25b9ab999f77182f0cd3bc085", "to": "0x87ac99835e67168d4f9a40580f8f5c33550ba88b", "gas": "0x100000", "gasPrice": "0x5d21dba00", "value": "0x0", "input": "0x8ada066e"}]

    EthEstimateGasResp:
      type: object
      properties:
        result:
          type: string
          format: hex
          description: The amount of gas used.
          example: "0x5208"

