openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/getSpamThrottlerWhiteList:
    post:
      operationId: getSpamThrottlerWhiteList
      summary: "[getSpamThrottlerWhiteList]"
      description: |
        Get spam throttler white list

        **JSONRPC:** `admin_getSpamThrottlerWhiteList`

      tags:
        - admin

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/GetSpamThrottlerWhiteListReq"

      responses:
        200:
          description: Get spam throttler white list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/GetSpamThrottlerWhiteListResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/getSpamThrottlerWhiteList.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminGetSpamThrottlerWhiteListExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/admin/getSpamThrottlerWhiteList.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/getSpamThrottlerWhiteList.py"

components:
  schemas:
    GetSpamThrottlerWhiteListReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'admin_getSpamThrottlerWhiteList'

    GetSpamThrottlerWhiteListResp:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/Address"
          example: ["0xfdeedbb2fe5b48d5b49e435ba00e0358740d0cf5"]
