openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: governance
    description: klaytn governance API
#  - name: RewardSpec
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/RewardSpec" />
x-tagGroups:
  - name: Governance
    tags:
      - governance
  - name: Models
    tags:
      - RewardSpec
servers:
  - url: http://localhost:7151
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:
  # governance
  /governance/votes:
    $ref: ./votes.yaml#/paths/~1governance~1votes
  /governance/idxCache:
    $ref: ./idxCache.yaml#/paths/~1governance~1idxCache
  /governance/idxCacheFromDb:
    $ref: ./idxCacheFromDb.yaml#/paths/~1governance~1idxCacheFromDb
  /governance/nodeAddress:
    $ref: ./nodeAddress.yaml#/paths/~1governance~1nodeAddress
  /governance/pendingChanges:
    $ref: ./pendingChanges.yaml#/paths/~1governance~1pendingChanges
  /governance/chainConfig:
    $ref: ./chainConfig.yaml#/paths/~1governance~1chainConfig
  /governance/myVotingPower:
    $ref: ./myVotingPower.yaml#/paths/~1governance~1myVotingPower
  /governance/myVotes:
    $ref: ./myVotes.yaml#/paths/~1governance~1myVotes
