openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getBlockTransactionCountByNumber:
    post:
      operationId: klayGetBlockTransactionCountByNumber
      summary: "[getBlockTransactionCountByNumber] Returns the number of transactions in a block matching the given block number."
      description: |
        Returns the number of transactions in a block matching the given block number.
        
        **JSONRPC:** `klay_getBlockTransactionCountByNumber`
        
        **NOTE:**  In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.

      tags:
        - klay.block

      parameters:
        - name: blockNumber
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "../../../components/schemas/klay/block/GetBlockTransactionCountByNumber.yaml#/components/schemas/KlayGetBlockTransactionCountByNumberReq"

      responses:
        200:
          description: Returns integer of the number of transactions in this block.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        description: Integer of the number of transactions in this block.
                        example: "0xa"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/block#klay_getblocktransactioncountbynumber
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/block/getBlockTransactionCountByNumber.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""
