openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getStorageAt:
    post:
      operationId: klayGetStorageAt
      summary: "[getStorageAt] Returns the value from a storage position at a given address."
      description: |
        Returns the value from a storage position at a given address.

        **JSONRPC:** `klay_getStorageAt`

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.*
      tags:
        - klay.block

      parameters:
        - name: storageAddress
          required: true
          schema:
            type: string
            format: 20-byte DATA
          description: Address of the storage.
          in: query
        - name: position
          required: true
          schema:
            type: string
            format: hex
          description: Integer of the position in the storage.
          in: query
        - name: blockNumberOrHash
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "../../../components/schemas/klay/block/GetStorageAt.yaml#/components/schemas/KlayGetStorageAtReq"

      responses:
        default:
          description: Returns the value from a storage position at a given address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: DATA
                        description: The value at this storage position.
                        example: "0x00000000000000000000000000000000000000000000000000000000000004d2"
      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/block#klay_getstorageat
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/block/getStorageAt.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""
