openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/syncing:
    post:
      operationId: syncing
      summary: "[syncing]"
      description: |
        Returns an object with data about the sync status or false.

        **JSONRPC:** `klay_syncing`

      tags:
        - klay

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: klay_syncing

      responses:
        200:
          description: Returns Object|Boolean, an object with sync status data or false when not syncing
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlaySyncingResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/block/syncing.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/block/syncing.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/block/syncing.py"

components:
  schemas:
    KlaySyncingResp:
      type: object
      properties:
        result:
          oneOf:
            - $ref: "#/components/schemas/SyncingObject"
            - type: boolean
              example: false

    SyncingObject:
      title: SyncingObject
      type: object
      required:
        - startingBlock
        - currentBlock
        - highestBlock
        - pulledStates
        - knownStates
      properties:
        startingBlock:
          type: string
          format: hex
          description: The block at which the import started (will only be reset, after the sync reached his head).
        currentBlock:
          type: string
          format: hex
          description: The current block, same as klay_blockNumber.
        highestBlock:
          type: string
          format: hex
          description: The estimated highest block.
        pulledStates:
          type: string
          format: hex
          description: The number of state entries processed until now. If the sync mode is not "fast", zero is returned.
        knownStates:
          type: string
          format: hex
          description: The number of known state entries that still need to be pulled. If the sync mode is not "fast", zero is returned.
      example:
          {
            "currentBlock": "0x3e31e",
            "highestBlock": "0x827eef",
            "knownStates": "0x0",
            "pulledStates": "0x0",
            "startingBlock": "0x0"
          }
