openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/setMaxSubscriptionPerWSConn:
    post:
      operationId: setMaxSubscriptionPerWSConn
      summary: "admin_setMaxSubscriptionPerWSConn"
      description: |
        The setMaxSubscriptionPerWSConn is an administrative method that sets the maximum allowed number of subscriptions per single WebSocket connection. For example, if the maximum number is set to five and a user requests more than five subscriptions through the klay_subscribe API, an error message "Maximum 5 subscriptions are allowed for a WebSocket connection" will be displayed. This feature is supported since Klaytn 1.6.0.

        **JSONRPC:** `admin_setMaxSubscriptionPerWSConn`

      tags:
        - admin

      parameters:
        - name: limit
          required: true
          schema:
            type: integer
          description: The maximum allowed number of subscriptions per single WebSocket connection.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/SetMaxSubscriptionPerWSConnReq"

      responses:
        200:
          description: Return null if the limit is set successfully; otherwise, it returns an error message.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/SetMaxSubscriptionPerWSConnResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/setMaxSubscriptionPerWSConn.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminSetMaxSubscriptionPerWSConnExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/setMaxSubscriptionPerWSConn.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/setMaxSubscriptionPerWSConn.py"

components:
  schemas:
    SetMaxSubscriptionPerWSConnReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_setMaxSubscriptionPerWSConn'
        params:
          type: array
          description: The maximum allowed number of subscriptions per single WebSocket connection.
          items:
            type: integer
            title: Limit
            example: 5

    SetMaxSubscriptionPerWSConnResp:
      type: object
      properties:
        result:
          type: string
          nullable: true
          description: null if the limit is set successfully; otherwise, it returns an error message.
          default: null





