openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/miscellaneous/submitHashrate:
    post:
      summary: "[Miscellaneous] eth_submitHashrate"
      tags:
        - eth
      operationId: submitHashrate
      description: |
        Used for submitting mining hashrate.
        
        Please note that it always return false because there is no PoW mechanism in Klaytn.
        
        **JSONRPC:** `eth_submitHashrate`

      parameters:
        - name: hashrate
          in: query
          description: A hexadecimal string representation (32 bytes) of the hash rate.
          required: true
          schema:
            type: string
            format: 32-byte DATA
        - name: id
          in: query
          description: A random hexadecimal(32 bytes) ID identifying the client.
          required: true
          schema:
            type: string
            format: 32-byte DATA

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthSubmitHashrateReq"

      responses:
        200:
          description: Returns true if submitting went through succesfully and false otherwise.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthSubmitHashrateResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/miscellaneous/submitHashrate.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/miscellaneous/EthSubmitHashrateExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/miscellaneous/submitHashrate.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/miscellaneous/submitHashrate.py"

components:
  schemas:
    EthSubmitHashrateReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'eth_submitHashrate'
        params:
          type: array
          items:
            properties:
              Hashrate:
                title: Hashrate
                description: A hexadecimal string representation (32 bytes) of the hash rate.
                type: string
                format: 32-byte DATA
              ID:
                title: Id
                description: A random hexadecimal(32 bytes) ID identifying the client.
                type: string
                format: 32-byte DATA
          example: ["0x5", "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"]

    EthSubmitHashrateResp:
      type: object
      properties:
        result:
          type: boolean
          description: Returns true if submitting went through succesfully and false otherwise.
          example: false
