openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /subbridge/parentOperatorNonce:
    post:
      summary: "subbridge_parentOperatorNonce"
      tags:
        - subbridge
      operationId: parentOperatorNonce
      description: |
        The subbridge_parentOperatorNonce returns the balance of the parent operator account.

        **JSONRPC:** `subbridge_parentOperatorNonce`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/parentOperatorNonceReq"

      responses:
        200:
          description: Integer of the current balance of the parent operator account.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/parentOperatorNonceResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/subbridge/parentOperatorNonce.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/eth/miscellaneous/txPending.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/eth/miscellaneous/txPending.py"

components:
  schemas:
    parentOperatorNonceReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'subbridge_parentOperatorNonce'
    parentOperatorNonceResp:
      type: object
      properties:
        result:
          type: number
          description: Integer of the number of transactions sent from the parent operator account.
          example: 1348