openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /subbridge/parentOperatorBalance:
    post:
      summary: "subbridge_parentOperatorBalance"
      tags:
        - subbridge
      operationId: parentOperatorBalance
      description: |
        The subbridge_parentOperatorBalance returns the balance of the parent operator account.

        **JSONRPC:** `subbridge_parentOperatorBalance`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/parentOperatorBalanceReq"

      responses:
        200:
          description: Integer of the current balance of the parent operator account.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/parentOperatorBalanceResp"

      x-codeSamples:
        # - lang: "Shell"
        #   label: "Curl"
        #   source:
        #     $ref: "../../code-samples/curl/subbridge/parentOperatorBalance.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "JavaScript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/eth/miscellaneous/txPending.js"
        # - lang: "Python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/eth/miscellaneous/txPending.py"

components:
  schemas:
    parentOperatorBalanceReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'subbridge_parentOperatorBalance'
    parentOperatorBalanceResp:
      type: object
      properties:
        result:
          type: number
          description: Integer of the current balance of the parent operator account.
          example: 1e+50