openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getTransactionBySenderTxHash:
    post:
      operationId: getTransactionBySenderTxHash
      summary: "[Transaction] klay_getTransactionBySenderTxHash"
      description: |
        Returns the information about a transaction requested by sender transaction hash. This API works only on RPC call, not on JavaScript console. Please note that this API returns correct result only if indexing feature is enabled by --sendertxhashindexing. This can be checked by call klay_isSenderTxHashIndexingEnabled.

        **JSONRPC:** `klay_getTransactionBySenderTxHash`

      tags:
        - klay

      parameters:
        - name: transactionHash
          required: true
          schema:
            type: string
            format: 32-byte DATA
          description: Hash of a transaction that is signed only by the sender.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetTransactionBySenderTxHashReq"

      responses:
        200:
          description: Returns information about a transaction by block number and transaction index position.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetTransactionBySenderTxHashResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/transaction/getTransactionBySenderTxHash.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/transaction/KlayGetTransactionBySenderTxHashExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/transaction/getTransactionBySenderTxHash.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/transaction/getTransactionBySenderTxHash.py"

components:
  schemas:
    KlayGetTransactionBySenderTxHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getTransactionBySenderTxHash'
        params:
          type: array
          description: Hash of a transaction that is signed only by the sender.
          items:
              type: string
              format: 32-byte DATA
              title: TransactionHash
              description: Hash of a transaction that is signed only by the sender.
          example:  ["0x18fe9e1007da7d20aad77778557fb8acc58c80054daba65124c8c843aadd3478"]

    KlayGetTransactionBySenderTxHashResp:
      type: object
      properties:
        result:
          $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TransactionObject"
