openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/newFilter:
    post:
      operationId: newFilter
      summary: "[newFilter]"
      description: |
        Creates a filter object, based on filter options, to notify when the state changes (logs).
        - To check if the state has changed, call eth_getFilterChanges.
        - To obtain all logs matching the filter created by eth_newFilter, call eth_getFilterLogs.

        **A note on specifying topic filters:** Topics are order-dependent. A transaction with a log with topics [A, B] will be matched by the following topic filters:
        - [] "anything"
        - [A] "A in first position (and anything after)"
        - [null, B] "anything in first position AND B in second position (and anything after)"
        - [A, B] "A in first position AND B in second position (and anything after)"
        - [[A, B], [A, B]] "(A OR B) in first position AND (A OR B) in second position (and anything after)"

        **JSONRPC:** `eth_newFilter`

      tags:
        - eth

      parameters:
        - name: fromBlock
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          description: |
            (optional, default: "latest") Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter.
          in: query
        - name: toBlock
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          description: |
            (optional, default: "latest") Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter.
          in: query
        - name: address
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
          description: |
            (optional) Contract address or a list of addresses from which logs should originate.
          in: query
        - name: topics
          required: false
          schema:
            $ref: "#/components/schemas/Topics"
          description: |
            (optional) Array of 32-byte DATA topics. Topics are order-dependent. Each topic can also be an array of DATA with "or" options.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthNewFilterReq"

      responses:
        200:
          description: Returns an array of all logs matching filter with given id. See eth_getFilterChanges.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthNewFilterResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/filter/newFilter.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""

components:
  schemas:
    EthNewFilterReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'eth_newFilter'
        params:
          type: array
          items:
            anyOf:
              - allOf:
                  - title: fromBlock
                  - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              - allOf:
                  - title: toBlock
                  - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              - $ref: "#/components/schemas/Topics"
          example:  [{"fromBlock":"earliest","toBlock":"latest","address":"0x87ac99835e67168d4f9a40580f8f5c33550ba88b","topics":["0xd596fdad182d29130ce218f4c1590c4b5ede105bee36690727baa6592bd2bfc8"]}]

    EthNewFilterResp:
      type: object
      properties:
        result:
          type: string
          format: hex
          description: A filter id
          example: 0xd32fd16b6906e67f6e2b65dcf48fc272

    # Addresses:
    #   oneOf:
    #     - type: array
    #       items:
    #         anyOf:
    #           - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
    #     - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"

    Topics:
      type: array
      items:
        type: string
        format: 32-byte DATA
