openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/gas/feeHistory:
    post:
      operationId: feeHistory
      summary: "[Gas] klay_feeHistory"
      description: |
        Returns historical gas information for a range of blocks.

        **NOTE:** This API is effective after Klaytn v1.8.0

        **JSONRPC:** `klay_feeHistory`
      tags:
        - klay

      parameters:
        - name: blockCount
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockCount"
          description: Number of blocks in the requested range.
          in: query
        - name: lastBlock
          in: query
          description: Highest block of the requested range. Can be a number or "latest".
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
        - name: rewardPercentiles
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/RewardPercentiles"
          description:  A monotonically increasing list of percentile (between 0 and 100) values. For each block in the requested range, the transactions will be sorted in ascending order by effective tip per gas and sampled at the specified percentiles.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayFeeHistoryReq"

      responses:
        200:
          description: Returns historical gas information for a range of blocks.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayFeeHistoryResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/gas/feeHistory.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/gas/KlayFeeHistoryExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/gas/feeHistory.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/gas/feeHistory.py"

components:
  schemas:
    KlayFeeHistoryReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_feeHistory'
        params:
          type: array
          items:
            properties:
              BlockCount:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockCount"
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              rewardPercentiles:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/RewardPercentiles"
                required: false
          example:  ["0x10", "latest", [0.1, 0.2, 0.3]]

    KlayFeeHistoryResp:
        type: object
        properties:
            result:
              type: object
              required:
                - oldestBlock
                - baseFeePerGas
                - gasUsedRatio
              properties:
                oldestBlock:
                  type: string
                  format: Hexadecimal
                  description: Lowest number block of returned range.
                baseFeePerGas:
                  $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BaseFeePerGas"
                gasUsedRatio:
                  type: array
                  items:
                    type: number
                    format: float
                  description: An array of block gas used ratios. Measures the network congestion level. These are calculated as the ratio of block gas used and [KIP-71 MAX_BLOCK_GAS_USED_FOR_BASE_FEE](https://kips.klaytn.foundation/KIPs/kip-71). If the ratio is above 1, then 1 is returned.
                reward:
                  $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Reward"
              example:
                {
                  "oldestBlock": "0xa5b",
                  "reward": [
                    [ "0x0", "0x0", "0x0" ],
                    [ "0x5d21dba00", "0x5d21dba00", "0x5d21dba00" ]
                  ],
                  "baseFeePerGas": [ "0x0", ..., "0x0" ],
                  "gasUsedRatio": [ 0, ..., 0.0002963777000002964 ]
                }
