openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/stacks:
    post:
      operationId: stacks
      summary: "[stacks]"
      description: |
        Returns a printed representation of the stacks of all goroutines.
        
        **JSONRPC:** `debug_stacks`

      tags:
        - debug

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/StacksReq"

      responses:
        200:
          description: The stack information of all goroutines.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/StacksResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/runtimeDebugging/stacks.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klaytnDebug/runtimeDebugging/DebugStacksExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
           $ref: "../../../code-samples/javascript/debug/runtimeDebugging/stacks.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klaytnDebug/runtimeDebugging/stacks.py"

components:
  schemas:
    StacksReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'debug_stacks'

    StacksResp:
      type: object
      properties:
        result:
            type: string
            description: The structured metrics collected by the node.The stack information of all goroutines.
            example: "goroutine 76176 [running]:\ngithub.com/klaytn/klaytn/api/debug.(*HandlerT).Stacks(0xc0002ce050, 0x0, 0x0)\n\t/private/tmp/klaytn-20181001-13887-zbyv2z/build/_workspace/src/github.com/klaytn/klaytn/api/debug/api.go:173 +0x74\nreflect.Value.call(0xc01867c660, 0xc000231bd8, 0x13, 0x4b26ca7, 0x4, 0xc008d8b7c0, 0x1, 0x1, 0x30, 0xc0323211d0 ..."
           


