openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/chaindbProperty:
    post:
      operationId: chaindbProperty
      summary: "[chaindbProperty]"
      description: |
        ChaindbProperty returns leveldb properties of the key-value database.

        **JSONRPC:** `debug_chaindbProperty`
      tags:
        - debug

      parameters:
        - name: string
          required: true
          schema:
            type: string
          description: string
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/chaindbPropertyReq"

      responses:
        200:
          description: Return string
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        example: string


      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/others/chaindbProperty.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: ""
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    chaindbPropertyReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_chaindbProperty'
        params:
          type: array
          items:
            type: string
          example: ["string"]