openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/accounts:
    post:
      operationId: accounts
      summary: "[accounts] Returns a list of addresses owned by client."
      description: |
        Returns a list of addresses owned by client.
        
        **JSONRPC:** `klay_accounts`

      tags:
        - klay

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                    - params
                  properties:
                    method:
                      type: string
                      default: 'klay_accounts'

      responses:
        200:
          description: Addresses owned by the client
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayAccountsResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/account#klay_accounts
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/accounts.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/account/accounts.js"
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""

components:
  schemas:
    KlayAccountsResp:
      type: object
      properties:
        result:
          type: array
          items:
            anyOf:
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
          example:  ["0xc94770007dda54cF92009BFF0dE90c06F603a09f"]
