openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/setGCPercent:
    post:
      operationId: setGCPercent
      summary: "[runtimeDebug] debug_setGCPercent"
      description: |
        Sets the garbage collection target percentage. It returns the previous setting. A negative value disables GC.
        
        **JSONRPC:** `debug_setGCPercent`

      tags:
        - debug

      parameters:
        - name: Percent
          in: query
          description: Garbage collection target percentage.
          required: true
          schema:
            type: integer

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/SetGCPercentReq"

      responses:
        200:
          description: Previous garbage collection target percentage.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/SetGCPercentResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/runtimeDebugging/setGCPercent.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/runtimeDebugging/DebugSetGCPercentExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
           $ref: "../../../code-samples/javascript/debug/runtimeDebugging/setGCPercent.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/runtimeDebugging/setGCPercent.py"

components:
  schemas:
    SetGCPercentReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_setGCPercent'
        params: 
          type: array
          description: Garbage collection target percentage.
          items: 
            title: Percent
            type: integer
            example: [100]

    SetGCPercentResp:
      type: object
      properties:
        result:
            type: integer
            description: Previous garbage collection target percentage.
            example: 70  


