openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /kaia/transaction/getTransactionReceipt:
    post:
      operationId: .getTransactionReceipt
      summary: "[Transaction] kaia_getTransactionReceipt"
      description: |
        Returns the receipt of a transaction by transaction hash.
        
        **NOTE:** The receipt is not available for pending transactions.
        
        **JSONRPC:** `kaia_getTransactionReceipt`

      tags:
        - kaia

      parameters:
        - name: transactionHash
          required: true
          schema:
            type: string
            format: 32-byte DATA
          description: Hash of a transaction.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KaiaGetTransactionReceiptReq"

      responses:
        200:
          description: Returns a transaction receipt object, or null when no receipt was found.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KaiaGetTransactionReceiptResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/kaia/transaction/getTransactionReceipt.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/kaia/transaction/KaiaGetTransactionReceiptExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/kaia/transaction/getTransactionReceipt.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/kaia/transaction/getTransactionReceipt.py"

components:
  schemas:
    KaiaGetTransactionReceiptReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'kaia_getTransactionReceipt'
        params:
          type: array
          description: Hash of a transaction.
          items:
              type: string
              format: 32-byte DATA
              title: TransactionHash
              description: Hash of a transaction.
          example:  ["0xaca5d9a1ed8b86b1ef61431b2bedfc99a66eaefc3a7e1cffdf9ff53653956a67"]

    KaiaGetTransactionReceiptResp:
      type: object
      properties:
        result:
          $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TransactionReceipt"
