openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/stopSpamThrottler:
    post:
      operationId: stopSpamThrottler
      summary: "[stopSpamThrottler]"
      description: |
        Stop spam throttler

        **JSONRPC:** `admin_stopSpamThrottler`

      tags:
        - admin

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/StopSpamThrottlerReq"

      responses:
        200:
          description: Stop spam throttler
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/stopSpamThrottlerResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/stopSpamThrottler.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminStopSpamThrottlerExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/stopSpamThrottler.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    StopSpamThrottlerReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_stopSpamThrottler'
        params:
          type: array
          items:
            type: object
          example: [{}]

    stopSpamThrottlerResp:
      type: object
      properties:
        result:
          type: string
          example: null