openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/traceChain:
    post:
      summary: "[traceChain]"
      tags:
        - debug
      operationId: traceChain
      description: |
        Returns the structured logs created during the execution of EVM between two blocks (excluding start) as a JSON object. This endpoint must be invoked via debug_subscribe as follows:

        **NOTE:** Don't trace too many blocks at the same time as it can overuse machine resources.

        **JSONRPC:** `debug_traceChain`

      parameters:
        - name: startBlockNumber
          in: query
          description: Tracing start block number.
          required: true
          schema:
            type: integer
        - name: number
          in: query
          description: Tracing end block number.
          required: true
          schema:
            type: integer
        - name: options
          in: query
          description: Tracing options.
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TracingOptions"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/DebugTraceChainReq"

      responses:
        200:
          description: Returns the structured logs created during the execution of EVM between two blocks (excluding start) as a JSON object. 
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/DebugTraceChainResp"

      x-codeSamples:
        # - lang: "curl"
        #   label: "Curl"
        #   source:
        #     $ref: "../../../code-samples/curl/klaytnDebug/vMTracing/traceChain.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klaytnDebug/vMTracing/DebugTraceChainExample.java"
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #    $ref: "../../../code-samples/javascript/klaytnDebug/vMTracing/traceChain.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/klaytnDebug/vMTracing/traceChain.py"

components:
  schemas:
    DebugTraceChainReq:
      type: object
      properties:
        method:
          type: string
          default: debug_traceChain
        params:
          type: array
          example: []
          items:
            anyOf:
              - title: StartBlockNumber
                type: integer
                description: Tracing start block number.
              - title: EndBlockNumber
                type: integer
                description: Tracing end block number.
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TracingOptions"

    DebugTraceChainResp:
      type: object
      properties:
        result:
          type: object
          description: Returns the structured logs created during the execution of EVM between two blocks (excluding start) as a JSON object. 
