openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/traceBlockByNumber:
    post:
      summary: "[traceBlockByNumber]"
      tags:
        - debug
      operationId: traceBlockByNumber
      description: |
        Similar to debug_traceBlock, traceBlockByNumber accepts a block number and will replay the block that is already present in the database.

        **JSONRPC:** `debug_traceBlockByNumber`

      parameters:
        - name: block
          in: query
          description: The block number.
          required: true
          schema:
            type: number
        - name: options
          in: query
          description: Tracing options.
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TracingOptions"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/DebugTraceBlockByNumberReq"

      responses:
        200:
          description: The structured logs created during the execution of KLVM.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/DebugTraceBlockByNumberResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klaytnDebug/vMTracing/traceBlockByNumber.sh"
#        - lang: "java"
#          label: "Java"
#          source:
#            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthAccountsExample.java"
#        - lang: "javascript"
#          label: "Javascript"
#          source:
#            $ref: "../../../code-samples/javascript/eth/account/accounts.js"
#        - lang: "python"
#          label: "Python"
#          source:
#            $ref: "../../../code-samples/python/eth/account/accounts.py"

components:
  schemas:
    DebugTraceBlockByNumberReq:
      type: object
      properties:
        method:
          type: string
          default: debug_traceBlockByNumber
        params:
          type: array
          items:
            anyOf:
              - title: Block
                type: number
                description: The block number.
                example: 1449
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/TracingOptions"

    DebugTraceBlockByNumberResp:
      type: object
      properties:
        result:
          type: object
          description: The structured logs created during the execution of KLVM.
          example: [
            {
              result: {
                failed: false,
                gas: 247922,
                returnValue: "60806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806341c0e1b514610051578063cfae321714610068575b600080fd5b34801561005d57600080fd5b506100666100f8565b005b34801561007457600080fd5b5061007d610168565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156100bd5780820151818401526020810190506100a2565b50505050905090810190601f1680156100ea5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415610166573373ffffffffffffffffffffffffffffffffffffffff16ff5b565b606060018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102005780601f106101d557610100808354040283529160200191610200565b820191906000526020600020905b8154815290600101906020018083116101e357829003601f168201915b50505050509050905600a165627a7a72305820f4e74ca2266a24aabd6a8ee6c4e54ad49014e2faa152e49e7f9d927c932c72870029",
                structLogs: [{"pc":0,"op":"PUSH1","gas":891344,"gasCost":3,"depth":1,"stack":[],"memory":[],"storage":{}}, {...}, {...}, {...}, {...}]
              }
            }
          ]