openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /net/peerCount:
    post:
      operationId: peerCount
      summary: "net_peerCount"
      description: |
        Returns the number of peers currently connected to the client.
        
        **JSONRPC:** `net_peerCount`
      tags:
        - net
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: net_peerCount

      responses:
        200:
          description: Returns the number of peers currently connected to the client.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        description: Integer of the number of connected peers.
                        example: "0x3"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/net/peerCount.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/net/NetPeerCountExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/net/peerCount.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/net/peerCount.py"
