openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/filter/newBlockFilter:
    post:
      operationId: newBlockFilter
      summary: "[Filter] eth_newBlockFilter"
      description: |
        Creates a filter in the node, to notify when a new block arrives. To check if the state has changed, call eth_getFilterChanges.

        **JSONRPC:** `eth_newBlockFilter`

      tags:
        - eth

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: "eth_newBlockFilter"

      responses:
        200:
          description: A filter id.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        description: "A filter id."
                        example: "0xc2f2e8168a7e38b5d979d0f7084130ee"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/filter/newBlockFilter.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/filter/EthNewBlockFilterExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/filter/newBlockFilter.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref:  "../../../code-samples/python/eth/filter/newBlockFilter.py"
