yarn build head@v1.0.0 -o ../../site/web3klaytn.yaml
yarn build eth@v1.0.0 -o ../../site/namespace/eth-openapi.yaml
yarn build klay@v1.0.0 -o ../../site/namespace/klay-openapi.yaml
yarn build net@v1.0.0 -o ../../site/namespace/net-openapi.yaml
yarn build txpool@v1.0.0 -o ../../site/namespace/txpool-openapi.yaml
yarn build debug@v1.0.0 -o ../../site/namespace/debug-openapi.yaml
yarn build personal@v1.0.0 -o ../../site/namespace/personal-openapi.yaml
yarn build governance@v1.0.0 -o ../../site/namespace/governance-openapi.yaml
yarn build admin@v1.0.0 -o ../../site/namespace/admin-openapi.yaml
yarn build mainbridge@v1.0.0 -o ../../site/namespace/mainbridge-openapi.yaml
yarn build subbridge@v1.0.0 -o ../../site/namespace/subbridge-openapi.yaml
