openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /kaia/gas/lowerBoundGasPrice:
    post:
      operationId: .lowerBoundGasPrice
      summary: "[Gas] kaia_lowerBoundGasPrice"
      description: |
        Returns lower bound gas price.

        **JSONRPC:** `kaia_lowerBoundGasPrice`

      tags:
        - kaia

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: kaia_lowerBoundGasPrice

      responses:
        200:
          description: Returns lower bound gas price.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        description: Lower bound gas price.
                        example: "0xae9f7bcc00"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/kaia/gas/lowerBoundGasPrice.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/kaia/gas/KaiaLowerBoundGasPriceExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/kaia/gas/lowerBoundGasPrice.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/kaia/gas/lowerBoundGasPrice.py"
