openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/recoverFromTransaction:
    post:
      operationId: recoverFromTransaction
      summary: "[Miscellaneous] klay_recoverFromTransaction"
      description: |
        Using this API, users can recover from transaction data.


        **JSONRPC:** `klay_recoverFromTransaction`
      tags:
        - klay

      parameters:
        - name: rlpEncodedTransaction
          required: true
          schema:
            type: string
            format: N-byte DATA
          description: RLP encoded transaction
          in: query
        - name: blockNumberOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in default block parameter.
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayRecoverFromTransactionReq"

      responses:
        200:
          description: The result of recover from transaction.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        example: "0xe15cd70a41dfb05e7214004d7d054801b2a2f06b"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/miscellaneous/recoverFromTransaction.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/miscellaneous/KlayRecoverFromTransactionExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/miscellaneous/recoverFromTransaction.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/miscellaneous/recoverFromTransaction.py"

components:
  schemas:
    KlayRecoverFromTransactionReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_recoverFromTransaction'
        params:
          type: array
          items:
            properties:
              RLPEncodedTransaction:
                title: RLPEncodedTransaction
                description: RLP Encoded Transaction.
                type: string
                format: N-byte DATA
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          example: ["0x08f88608850ba43b7400827b0c94c40b6909eb7085590e1c26cb3becc25368e249e9880de0b6b3a764000094e15cd70a41dfb05e7214004d7d054801b2a2f06bf847f845820fe9a090421871e8fd77e08b6a72760006a15184a96cfc39c7486ea948d11fd830ae8aa05876248aa8dc0783d782e584e6f8d9bf977c698210a0eab3e754192d0954de65", "latest"]
