openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/getStorageAt:
    post:
      operationId: getStorageAt
      summary: "[Block] eth_getStorageAt"
      description: |
        Returns the value from a storage position at a given address

        **JSONRPC:** `eth_getStorageAt`
      tags:
        - eth

      parameters:
        - name: Address
          required: true
          in: query
          description: Address of the storage.
          schema:
            type: string
            format: 20-byte DATA
        - name: Quantity
          required: true
          in: query
          description: Integer of the position in the storage.
          schema:
            type: string
            format: hex
        - name: BlockNumberOrHashOrTag
          required: true
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in default block parameter, or block hash.
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthGetHeaderByHashReq"

      responses:
        200:
          description: The value at this storage position.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthGetHeaderByHashResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/block/getStorageAt.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/block/EthGetStorageAtExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/block/getStorageAt.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/block/getStorageAt.py"

components:
  schemas:
    EthGetHeaderByHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: "eth_getStorageAt"
        params:
          type: array
          items:
            properties:
              Address:
                type: string
                title: Address
                description: Address of the storage.
                format: 20-byte DATA
              Quantity:
                type: string
                title: Quantity
                description: Integer of the position in the storage.
                format: hex
              BlockNumberOrHashOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:
            ["0x295a70b2de5e3953354a6a8344e616ed314d7251", "0x0", "latest"]

    EthGetHeaderByHashResp:
      type: object
      properties:
        result:
          type: string
          format: DATA
          description: The value at this storage position.
          example: "0x00000000000000000000000000000000000000000000000000000000000004d2"
