/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountCreatedRequestAllOf model module.
 * @module model/AccountCreatedRequestAllOf
 * @version 1.10.0
 */
class AccountCreatedRequestAllOf {
    /**
     * Constructs a new <code>AccountCreatedRequestAllOf</code>.
     * @alias module:model/AccountCreatedRequestAllOf
     */
    constructor() { 
        
        AccountCreatedRequestAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountCreatedRequestAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountCreatedRequestAllOf} obj Optional instance to populate.
     * @return {module:model/AccountCreatedRequestAllOf} The populated <code>AccountCreatedRequestAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountCreatedRequestAllOf();

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccountCreatedRequestAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccountCreatedRequestAllOf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }

        return true;
    }


}



/**
 * @member {String} method
 * @default 'klay_accountCreated'
 */
AccountCreatedRequestAllOf.prototype['method'] = 'klay_accountCreated';

/**
 * @member {Object} params
 */
AccountCreatedRequestAllOf.prototype['params'] = undefined;






export default AccountCreatedRequestAllOf;

