/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountCreatedDefaultResponseAllOf model module.
 * @module model/AccountCreatedDefaultResponseAllOf
 * @version 1.10.0
 */
class AccountCreatedDefaultResponseAllOf {
    /**
     * Constructs a new <code>AccountCreatedDefaultResponseAllOf</code>.
     * @alias module:model/AccountCreatedDefaultResponseAllOf
     */
    constructor() { 
        
        AccountCreatedDefaultResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountCreatedDefaultResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountCreatedDefaultResponseAllOf} obj Optional instance to populate.
     * @return {module:model/AccountCreatedDefaultResponseAllOf} The populated <code>AccountCreatedDefaultResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountCreatedDefaultResponseAllOf();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccountCreatedDefaultResponseAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccountCreatedDefaultResponseAllOf</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} result
 */
AccountCreatedDefaultResponseAllOf.prototype['result'] = undefined;






export default AccountCreatedDefaultResponseAllOf;

