/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountCreatedRequestAllOf from './AccountCreatedRequestAllOf';
import JsonRpcRequest from './JsonRpcRequest';

/**
 * The AccountCreatedRequest model module.
 * @module model/AccountCreatedRequest
 * @version 1.10.0
 */
class AccountCreatedRequest {
    /**
     * Constructs a new <code>AccountCreatedRequest</code>.
     * @alias module:model/AccountCreatedRequest
     * @implements module:model/JsonRpcRequest
     * @implements module:model/AccountCreatedRequestAllOf
     * @param method {String} 
     * @param id {Number} Request ID, Random or Auto incrementation
     * @param jsonrpc {String} JSON-RPC Version (2.0)
     */
    constructor(method, id, jsonrpc) { 
        JsonRpcRequest.initialize(this, method, id, jsonrpc);AccountCreatedRequestAllOf.initialize(this);
        AccountCreatedRequest.initialize(this, method, id, jsonrpc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, method, id, jsonrpc) { 
        obj['method'] = method || 'klay_accountCreated';
        obj['id'] = id || 1;
        obj['jsonrpc'] = jsonrpc || '2.0';
    }

    /**
     * Constructs a <code>AccountCreatedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountCreatedRequest} obj Optional instance to populate.
     * @return {module:model/AccountCreatedRequest} The populated <code>AccountCreatedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountCreatedRequest();
            JsonRpcRequest.constructFromObject(data, obj);
            AccountCreatedRequestAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('jsonrpc')) {
                obj['jsonrpc'] = ApiClient.convertToType(data['jsonrpc'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccountCreatedRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccountCreatedRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AccountCreatedRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['jsonrpc'] && !(typeof data['jsonrpc'] === 'string' || data['jsonrpc'] instanceof String)) {
            throw new Error("Expected the field `jsonrpc` to be a primitive type in the JSON string but got " + data['jsonrpc']);
        }

        return true;
    }


}

AccountCreatedRequest.RequiredProperties = ["method", "id", "jsonrpc"];

/**
 * @member {String} method
 * @default 'klay_accountCreated'
 */
AccountCreatedRequest.prototype['method'] = 'klay_accountCreated';

/**
 * Request ID, Random or Auto incrementation
 * @member {Number} id
 * @default 1
 */
AccountCreatedRequest.prototype['id'] = 1;

/**
 * JSON-RPC Version (2.0)
 * @member {String} jsonrpc
 * @default '2.0'
 */
AccountCreatedRequest.prototype['jsonrpc'] = '2.0';

/**
 * @member {Object} params
 */
AccountCreatedRequest.prototype['params'] = undefined;


// Implement JsonRpcRequest interface:
/**
 * Method name
 * @member {String} method
 */
JsonRpcRequest.prototype['method'] = undefined;
/**
 * Request ID, Random or Auto incrementation
 * @member {Number} id
 * @default 1
 */
JsonRpcRequest.prototype['id'] = 1;
/**
 * JSON-RPC Version (2.0)
 * @member {String} jsonrpc
 * @default '2.0'
 */
JsonRpcRequest.prototype['jsonrpc'] = '2.0';
/**
 * @member {Array.<Object>} params
 */
JsonRpcRequest.prototype['params'] = undefined;
// Implement AccountCreatedRequestAllOf interface:
/**
 * @member {String} method
 * @default 'klay_accountCreated'
 */
AccountCreatedRequestAllOf.prototype['method'] = 'klay_accountCreated';
/**
 * @member {Object} params
 */
AccountCreatedRequestAllOf.prototype['params'] = undefined;




export default AccountCreatedRequest;

