/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRewardsBlockNumberOrTagParameter model module.
 * @module model/GetRewardsBlockNumberOrTagParameter
 * @version 1.10.0
 */
class GetRewardsBlockNumberOrTagParameter {
    /**
     * Constructs a new <code>GetRewardsBlockNumberOrTagParameter</code>.
     * @alias module:model/GetRewardsBlockNumberOrTagParameter
     * @param {(module:model/Number|module:model/String)} instance The actual instance to initialize GetRewardsBlockNumberOrTagParameter.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // the block number
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Number
            errorMessages.push("Failed to construct Number: " + err)
        }

        // the block tag [latest, pending, eariest]
        try {
            // validate array of string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid input. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `GetRewardsBlockNumberOrTagParameter` with oneOf schemas Number, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `GetRewardsBlockNumberOrTagParameter` with oneOf schemas Number, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>GetRewardsBlockNumberOrTagParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRewardsBlockNumberOrTagParameter} obj Optional instance to populate.
     * @return {module:model/GetRewardsBlockNumberOrTagParameter} The populated <code>GetRewardsBlockNumberOrTagParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        return new GetRewardsBlockNumberOrTagParameter(data);
    }

    /**
     * Gets the actaul instance, which can be <code>Number</code>, <code>String</code>.
     * @return {(module:model/Number|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actaul instance, which can be <code>Number</code>, <code>String</code>.
     * @param {(module:model/Number|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = GetRewardsBlockNumberOrTagParameter.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual intance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of GetRewardsBlockNumberOrTagParameter from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/GetRewardsBlockNumberOrTagParameter} An instance of GetRewardsBlockNumberOrTagParameter.
     */
    static fromJSON = function(json_string){
        return GetRewardsBlockNumberOrTagParameter.constructFromObject(JSON.parse(json_string));
    }
}


GetRewardsBlockNumberOrTagParameter.OneOf = ["Number", "String"];

export default GetRewardsBlockNumberOrTagParameter;

