/**
 * KLAYTN OPEN API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Result from './Result';

/**
 * The RewardsResp model module.
 * @module model/RewardsResp
 * @version 1.10.0
 */
class RewardsResp {
    /**
     * Constructs a new <code>RewardsResp</code>.
     * @alias module:model/RewardsResp
     */
    constructor() { 
        
        RewardsResp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RewardsResp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RewardsResp} obj Optional instance to populate.
     * @return {module:model/RewardsResp} The populated <code>RewardsResp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RewardsResp();

            if (data.hasOwnProperty('result')) {
                obj['result'] = Result.constructFromObject(data['result']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RewardsResp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RewardsResp</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          Result.validateJSON(data['result']);
        }

        return true;
    }


}



/**
 * @member {module:model/Result} result
 */
RewardsResp.prototype['result'] = undefined;






export default RewardsResp;

