openapi: "3.0.2"
info:
  title: eth OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/getCode:
    post:
      operationId: getCode
      summary: "[getCode] Returns code at a given address."
      description: |
        Returns code at a given address.

        **JSONRPC:** `eth_getCode`

      tags:
        - eth

      parameters:
        - name: address
          in: query
          description: Address
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
        - name: blockNumberOrHash
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthGetCodeReq"

      responses:
        200:
          description: Returns code at a given address.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthGetCodeResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/eth/account#eth_getcode
        description: ethtn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/account/getCode.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        #- lang: "javascript"
        #  label: "Javascript"
        #  source:
        #    $ref: ""
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""

components:
  schemas:
    EthGetCodeReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'eth_getCode'
        params:
          type: array
          items:
            anyOf:
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              - $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  ["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x2"]

    EthGetCodeResp:
      type: object
      properties:
        result:
          type: string
          format: DATA
          description: The code from the given address.
          example: "0x600160008035811a818181146012578301005b601b6001356025565b8060005260206000f25b600060078202905091905056"
